### ISSUE TITLE
Is this plugin still under maintenance?

### ISSUE THREAD

**Issue by psntr** [ttillberg/acf-vimeo-pro-data#11]
Hello,

While searching how I could simply use my vimeo pro account with ACF I found your plugin. With the latest Wordpress and ACF, the plugin seems out of date. What I noticed:

1) It re-write my htaccess?
2) After saving a post with a vimeo video inside the ACF field content disappeared. 

Are anyone still working on this plugin or it's no longer on development?
Thank you!
-J

**Comment by ttillberg** [comment]
Hey,

I just did some improvements on the `develop` branch the other day, give it a try if you have a chance, the UI is somewhat nicer. 

To answer your questions:

1. No it doesn't. AFAIR it creates a route to proxy Vimeo API calls. but as long as you're using a typical index.php catch-all it should work. 

2. So you're saying the field was reset after saving? But you still get the poster frame showing etc? Haven't had any complaints about that before... Any errors in the logs, console etc. ? Please give me some more clues and I'll help you debug.

Cheers,
T

**Comment by psntr** [comment]
Hi @ttillberg,
Thank you for your really fast reply.

I was about to write you back. I was a bit under stress therefore, I misconfigured my Apps in my Vimeo's dev account, I forgot the callback URL (default post URL in backend) and the scopes, set as "public private interact video_files". So that solved point 2. Now I can finally see the output of my videos!
And about the htaccess I don't get why it does that, so for the moment I will lock the htaccess rights.

Again thank you for the quick answer and thank you for this little gem.

**Comment by ttillberg** [comment]
Happy to hear it worked out. Not sure the callback URL is useful but definitely the "video_files" scope. I should add that to the README if not done already... Thanks for noticing. 

Regarding the `.htaccess`, it can't be caused by the plugin (unless indirectly somehow), I can swear I haven't written a line of code that would alter the filesystem.

BTW, like explained in the README, make sure you're using the GitHub updater plugin when you install, otherwise you won't get the next updates 😎

**Comment by psntr** [comment]
First thing in my list tomorrow morning. 

Yep you should add that scope thing in the README. Again thank you for your time!

p.s. I tested the develop version, if I notice anything, I will let you know.
